graph LR
  %% Memory Layer (System of Record / Reference Data)

  bc_001["💾 Correspondent Directory Management"]
  style bc_001 fill:#3498db,stroke:#333,stroke-width:2px,color:#fff
  bc_002["💾 Settlement Instruction Management"]
  style bc_002 fill:#3498db,stroke:#333,stroke-width:2px,color:#fff

  bc_001 --> bc_002
